"""Tiny netlist model: parts, pins, nets, ERC and output generators.

Each board file (board_a.py, board_b.py) builds a Board by calling Board.add().
build.py runs ERC and writes:
  - sheet tables (Markdown) with every part, pin and net
  - a KiCad S-expression netlist (.net) that Pcbnew can import (File > Import > Netlist)
  - a hand-assembly BOM and a JLC-format BOM (CSV)
  - a CPL template plus the rotation table that kicad_pos_to_jlc_cpl.py applies
"""
import csv
import datetime
import io
import re
import uuid
from collections import OrderedDict, defaultdict

from catalog import CATALOG

NC = None          # explicit no-connect


class Part:
    def __init__(self, board, ref, key, pins, sheet, value=None, dnp=False, note=""):
        if key not in CATALOG:
            raise KeyError(f"{ref}: catalog key {key!r} missing")
        self.board = board
        self.ref = ref
        self.key = key
        self.cat = CATALOG[key]
        self.value = value or self.cat["value"]
        self.footprint = self.cat["footprint"]
        self.sheet = sheet
        self.dnp = dnp
        self.note = note
        # pins: {pin_number: net} or {pin_number: (pin_name, net)}
        self.pins = OrderedDict()
        names = self.cat.get("pins", {})
        for num, v in pins.items():
            num = str(num)
            if isinstance(v, tuple):
                name, net = v
            else:
                name, net = names.get(num, "~"), v
            self.pins[num] = (name, net)
        expected = self.cat.get("pins")
        if expected:
            missing = [p for p in expected if p not in self.pins]
            extra = [p for p in self.pins if p not in expected]
            if missing or extra:
                raise ValueError(f"{ref} ({key}): missing pins {missing}, unknown pins {extra}")

    @property
    def uuid(self):
        return str(uuid.uuid5(uuid.NAMESPACE_URL, f"xtm-driver/{self.board.name}/{self.ref}"))


class Board:
    def __init__(self, name, title, sheets):
        self.name = name
        self.title = title
        self.sheets = sheets            # ordered list of (sheet id, sheet title)
        self.parts = OrderedDict()
        self.single_ok = set()          # nets allowed to have one connection (test points, spares)
        self.power_sources = {}         # net -> description of what drives it
        self.extras = []                # (label, catalog key, qty per board): BOM-only items, e.g. mating plugs

    def add(self, ref, key, pins, sheet, **kw):
        if ref in self.parts:
            raise ValueError(f"duplicate reference {ref}")
        if sheet not in dict(self.sheets):
            raise ValueError(f"{ref}: unknown sheet {sheet}")
        p = Part(self, ref, key, pins, sheet, **kw)
        self.parts[ref] = p
        return p

    # ---- two-terminal helpers -------------------------------------------------
    def two(self, ref, key, a, b, sheet, **kw):
        return self.add(ref, key, {"1": a, "2": b}, sheet, **kw)

    # ---- queries ----------------------------------------------------------------
    def nets(self):
        n = defaultdict(list)
        for p in self.parts.values():
            for num, (name, net) in p.pins.items():
                if net is not None:
                    n[net].append((p.ref, num, name))
        return dict(sorted(n.items(), key=lambda kv: _natkey(kv[0])))

    def erc(self):
        errors, warnings = [], []
        nets = self.nets()
        for net, nodes in nets.items():
            refs = {r for r, _, _ in nodes}
            if len(nodes) < 2 and net not in self.single_ok:
                errors.append(f"net {net} has a single connection: {nodes}")
            elif len(refs) < 2 and net not in self.single_ok:
                warnings.append(f"net {net} only connects pins of {refs}")
        for net in self.power_sources:
            if net not in nets:
                errors.append(f"power net {net} declared but unused")
        for p in self.parts.values():
            for num, (name, net) in p.pins.items():
                if net is None and not p.cat.get("nc_ok", True):
                    errors.append(f"{p.ref} pin {num} unconnected")
        return errors, warnings

    # ---- outputs ----------------------------------------------------------------
    def sheet_tables_md(self):
        out = io.StringIO()
        out.write(f"# {self.title}: sheet tables\n\n")
        out.write("Generated by `design/build.py` from `design/%s.py`. Every pin of every part is listed; "
                  "`NC` means deliberately unconnected. Net names in CAPS match the KiCad netlist.\n\n" % self.name)
        nets = self.nets()
        for sid, stitle in self.sheets:
            parts = [p for p in self.parts.values() if p.sheet == sid]
            if not parts:
                continue
            out.write(f"## Sheet {sid}: {stitle}\n\n")
            out.write("| Ref | Value | Part | Footprint | Pins (pin name: net) |\n| --- | --- | --- | --- | --- |\n")
            for p in sorted(parts, key=lambda p: _natkey(p.ref)):
                pins = "; ".join(f"{num} {name}: {net or 'NC'}" if name not in ("~", "") else f"{num}: {net or 'NC'}"
                                 for num, (name, net) in p.pins.items())
                val = p.value + (" (DNP)" if p.dnp else "")
                mpn = p.cat.get("mpn", "")
                out.write(f"| {p.ref} | {val} | {mpn} | `{p.footprint}` | {pins} |\n")
            notes = [p for p in parts if p.note]
            if notes:
                out.write("\nNotes:\n\n")
                for p in notes:
                    out.write(f"- **{p.ref}**: {p.note}\n")
            out.write("\n")
        out.write("## Net list\n\n| Net | Connections |\n| --- | --- |\n")
        for net, nodes in nets.items():
            out.write(f"| {net} | " + ", ".join(f"{r}.{n}" for r, n, _ in sorted(nodes, key=lambda x: (_natkey(x[0]), _natkey(x[1])))) + " |\n")
        return out.getvalue()

    def kicad_netlist(self):
        def q(s):
            return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'
        lines = ['(export (version "E")',
                 f'  (design (source {q(self.name + ".py")}) (date {q(datetime.date.today().isoformat())}) '
                 f'(tool {q("xtm-driver netlib")}))',
                 "  (components"]
        for p in self.parts.values():
            lib, part = p.cat.get("symbol", "Device:R").split(":", 1)
            fields = []
            for k in ("mpn", "manufacturer", "lcsc"):
                if p.cat.get(k):
                    fields.append(f"(field (name {q(k.upper() if k == 'lcsc' else k.capitalize())}) {q(p.cat[k])})")
            if p.dnp:
                fields.append('(field (name "DNP") "DNP")')
            lines.append(f"    (comp (ref {q(p.ref)})")
            lines.append(f"      (value {q(p.value)})")
            lines.append(f"      (footprint {q(p.footprint)})")
            if fields:
                lines.append("      (fields " + " ".join(fields) + ")")
            lines.append(f"      (libsource (lib {q(lib)}) (part {q(part)}) (description {q(p.cat.get('desc', ''))}))")
            lines.append(f'      (sheetpath (names "/") (tstamps "/"))')
            lines.append(f"      (tstamps {q(p.uuid)}))")
        lines.append("  )")
        lines.append("  (nets")
        for code, (net, nodes) in enumerate(self.nets().items(), start=1):
            lines.append(f"    (net (code {q(code)}) (name {q(net)})")
            for r, n, name in nodes:
                pf = "" if name in ("~", "") else f" (pinfunction {q(name)})"
                lines.append(f"      (node (ref {q(r)}) (pin {q(n)}){pf})")
            lines[-1] += ")"
        lines.append("  )")
        lines.append(")")
        return "\n".join(lines) + "\n"

    def bom_hand(self, sets):
        groups = OrderedDict()
        for p in self.parts.values():
            k = (p.key, p.value, p.dnp)
            groups.setdefault(k, []).append(p.ref)
        out = io.StringIO()
        w = csv.writer(out)
        w.writerow(["Refs", "Qty/board", f"Qty for {sets} boards (+spares)", "Value", "Description", "Manufacturer",
                    "MPN", "Digi-Key", "Mouser", "LCSC", "Footprint", "Placement", "Status", "Notes"])
        for (key, value, dnp), refs in sorted(groups.items(), key=lambda kv: _natkey(kv[1][0])):
            c = CATALOG[key]
            n = len(refs)
            if dnp:
                buy = 0
            else:
                buy = n * sets + _spares(n, c)
            w.writerow([" ".join(sorted(refs, key=_natkey)), 0 if dnp else n, buy, value, c.get("desc", ""),
                        c.get("manufacturer", ""), c.get("mpn", ""), c.get("digikey", ""), c.get("mouser", ""),
                        c.get("lcsc", ""), c["footprint"].split(":")[-1], "not fitted" if dnp else c.get("place", "stencil"),
                        c.get("status", ""), c.get("note", "")])
        for label, key, n in self.extras:
            c = CATALOG[key]
            w.writerow([label, n, n * sets + _spares(n, c), c["value"], c.get("desc", ""), c.get("manufacturer", ""),
                        c.get("mpn", ""), c.get("digikey", ""), c.get("mouser", ""), c.get("lcsc", ""), "-",
                        c.get("place", "off-board"), c.get("status", ""), c.get("note", "")])
        return out.getvalue()

    def bom_jlc(self):
        groups = OrderedDict()
        for p in self.parts.values():
            if p.dnp or p.cat.get("no_bom"):
                continue
            k = (p.key, p.value)
            groups.setdefault(k, []).append(p.ref)
        out = io.StringIO()
        w = csv.writer(out)
        w.writerow(["Comment", "Designator", "Footprint", "LCSC Part #", "JLC class", "Loading fee note"])
        for (key, value), refs in sorted(groups.items(), key=lambda kv: _natkey(kv[1][0])):
            c = CATALOG[key]
            cls = c.get("jlc", "")
            # JLC's price page, September 2026: Economic PCBA charges $3.07 feeder loading per unique
            # Extended part; Standard PCBA charges $1.53 for every part type, Basic included.
            fee = {"Basic": "none (Economic PCBA)", "Preferred": "none (Economic PCBA)",
                   "Extended": "~$3 per unique part per order (Economic PCBA)"}.get(cls, "not placed by JLC")
            if c.get("status") == "describe" and cls:
                cls += " (expected; pick the part in JLC's BOM tool)"
            w.writerow([value, ",".join(sorted(refs, key=_natkey)), c["footprint"].split(":")[-1], c.get("lcsc", ""), cls or "-", fee])
        return out.getvalue()

    def cpl_template(self):
        out = io.StringIO()
        w = csv.writer(out)
        w.writerow(["Designator", "Mid X", "Mid Y", "Layer", "Rotation"])
        for p in self.parts.values():
            if p.dnp or p.cat.get("no_bom"):
                continue
            w.writerow([p.ref, "", "", "Top", ""])
        return out.getvalue()


def _spares(n, c):
    """Extra parts to buy beyond the board count: passives get generous spares, ICs one."""
    if "spares" in c:
        return c["spares"]
    kind = c.get("kind", "")
    if kind in ("R", "C", "FB", "LED"):
        return max(10, n * 2)
    if kind in ("mech",):
        return 0
    return 1


def _natkey(s):
    return [int(t) if t.isdigit() else t for t in re.split(r"(\d+)", str(s))]
